export const gridData = [
  {
    id: 1,
    costCenter: 'Debra Ortiz',
    voucherType: 'type',
    DefaultAccount: 23423,
    defaultAccount: 52,
    accountTitle: 38,
    balanceSide: 2343,
    startingNumber: 3,
    currentNumber: 33,
    numberOfDigits: 32,
  },
  {
    id: 2,
    costCenter: 'Ortiz',
    voucherType: 'type',
    DefaultAccount: 23423,
    defaultAccount: 52,
    accountTitle: 38,
    balanceSide: 2343,
    startingNumber: 3,
    currentNumber: 33,
    numberOfDigits: 32,
  },
];
